version = 1

exclude_patterns = [
    ".github/**",
    ".serverless/**",
    "bin/**",
    "**/node_modules/"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/vinicius73/gamer-feed/src"]
  dependencies_vendored = false

[[transformers]]
name = "gofmt"
enabled = true
