linters:
  disable:
    - gochecknoglobals
    - godox
    - wsl
    - errcheck
    - wrapcheck
    - depguard
    - tagliatelle
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - (or|er)$
      - tea.Model
      - tea.Msg
  exhaustruct:
    exclude:
      - ".*_test.go"
      - 'github.com/urfave/cli/v2\.Command$'
      - 'github.com/urfave/cli/v2\.App$'
  varnamelen:
    ignore-type-assert-ok: true
    ignore-decls:
      - el Element
      - s spinner.New
      - wg sync.WaitGroup
    ignore-names:
      - err
