linters:
  disable:
    - gochecknoglobals
    - godox
    - wsl
    - errcheck
    - wrapcheck
    - depguard
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
