linters:
  disable:
    - gochecknoglobals
    - godox
    - wsl
    - errcheck
    - wrapcheck
    - depguard
    - tagliatelle
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  varnamelen:
    ignore-type-assert-ok: true
    ignore-decls:
      - el Element
    ignore-names:
      - err
