linters:
  disable:
    - gochecknoglobals
    - godox
    - wsl
    - errcheck
    - wrapcheck
    - depguard
    - tagliatelle
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - (or|er)$
      - tea.Model
      - tea.Msg
      - model.IEntry
      - T
  exhaustruct:
    exclude:
      - ".*_test.go"
      - 'github.com/urfave/cli/v2\.Command$'
      - 'github.com/urfave/cli/v2\.App$'
      - 'github.com/urfave/cli/v2\.IntFlag$'
      - 'github.com/urfave/cli/v2\.StringFlag$'
      - 'github.com/urfave/cli/v2\.StringSliceFlag$'
      - 'github.com/urfave/cli/v2\.BoolFlag$'
      - 'github.com/urfave/cli/v2\.Int64Flag$'
      - 'github.com/urfave/cli/v2\.Int64SliceFlag$'
      - gopkg.in/telebot.v3\.Document
  varnamelen:
    ignore-type-assert-ok: true
    ignore-decls:
      - el Element
      - s spinner.New
      - wg *sync.WaitGroup
      - wg sync.WaitGroup
      - db badger.DB
    ignore-names:
      - err
      - db

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - varnamelen
        - exhaustruct
