name: Super-Linter
on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: cp .env.example .env
      - run: make init

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_GO: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}